# Generated by Django 3.2.19 on 2023-05-28 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=3)),
                ('district', models.CharField(max_length=30)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=52)),
                ('continent', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=26)),
                ('surface_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indep_year', models.IntegerField()),
                ('population', models.IntegerField()),
                ('life_expectancy', models.DecimalField(decimal_places=1, max_digits=3)),
                ('gnp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gnp_old', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local_name', models.CharField(max_length=45)),
                ('government_name', models.CharField(max_length=45)),
                ('head_of_state', models.CharField(max_length=60)),
                ('capital', models.IntegerField()),
                ('code2', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='countrylanguage',
            fields=[
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='panorbit_app.country')),
                ('language', models.CharField(max_length=30)),
                ('is_official', models.CharField(max_length=1)),
                ('percentage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
